### ISSUE TITLE
A snafu with the ACS_2010_14 file

### ISSUE THREAD

**Issue by mwoluchem** [NeighborhoodInfoDC/IPUMS#1]
Hi team, 

It appears that there's a small glitch in the ACS_yyyy file that won't allow the IPUMS data to upload properly. Looks like it's something to do with the interaction between the Hud_inc_all macro and the ACS_2010_14 program but I'm not certain. Please excuse the name of this commit, this should be named for an IPUMS data update. I thought each program got its own commit, my apologies.

Anyway, the following fatal errors occur in the ACS_2010_14 file:

1,  An issue with the UIAUTOS and DCAUTOS references:

```
ERROR: At least one file associated with fileref UIAUTOS is still in use.
ERROR: Error in the FILENAME statement.
```

   ERROR: At least one file associated with fileref DCAUTOS is still in use.
   ERROR: Error in the FILENAME statement
1. The format statement that carries over from past ACS_yyyy updates includes variables that do not exist in the 2010_14 data, leading to a large amount of warnings. 
2. There seems to be an error in the HUD_inc_all macro that neither Rob nor I could find. There are hundreds of errors (one for each _N_) that appear when trying to run the ACS_2010_14 program that say the following: 

ERROR: [Hud_inc_all] _N_=1 YEAR=2014 not supported.
ERROR: [Hud_inc_all] _N_=2 YEAR=2014 not supported....

I've run through the Hud_inc_all program to see what could be the problem but it's not apparent to me, looks like there's just some issue with 2014. Any ideas?

Thanks so much,
Maia

**Comment by ptatian** [comment]
Hi Maya,

Thanks for flagging this. Looks like this set of programs wasn't yet adapted for the new SAS1 setup. The macro files have not been moved to the Macros folder. You need to look in the Prog folder and move all of the files that are autocall macro definitions into Macros. This includes the Hud_inc_all.sas file. Otherwise, the program doesn't know where to find the macros.

Once you have done that, restart with a new SAS session so that you are sure to get the latest macro definitions. 

Also, you should not be making commits directly to the Master branch. You should have [created a separate branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) for the changes you are making. Typically, we first create an issue in the repository for the task we are about to do. Then we create a new branch based on the type of task. The actual branch name will be _xxxx-#issue_, where _xxxx_ is  _update_ for data updates; _develop_ for program enhancements; or _bugfix_ for correcting coding errors. _issue_ is the issue number for the task. So, for example, a data update identified as issue #12 would be worked on in the branch _update-#12_.

Once the work is complete, you can [make a pull request](https://help.github.com/articles/using-pull-requests/) to merge the branch changes into the Master branch. The entire process is illustrated in this [workflow chart](https://urbanorg.app.box.com/files/0/f/5384452081/1/f_43671646405). 

Please let me or @rpitingolo know if you have any questions.

**Comment by ptatian** [comment]
@mwoluchem Going back over older issues and came across this one. I'm assuming that you haven't made any further progress? Please let me know. Thanks.

**Comment by lhendey** [comment]
@mwoluchem @ptatian @rpitingolo - the data did get updated,my assumption is that both this issue and #2 should be closed.
